import { hilog } from '@kit.PerformanceAnalysisKit';
import { describe, beforeAll, beforeEach, afterEach, afterAll, it, expect } from '@ohos/hypium';

export default function abilityTest() {
  describe('ActsAbilityTest', () => {
    
    beforeAll(() => {
      
      
    })
    beforeEach(() => {
      
      
      
    })
    afterEach(() => {
      
      
      
    })
    afterAll(() => {
      
      
    })
    it('assertContain', 0, () => {
      
      hilog.info(0x0000, 'testTag', '%{public}s', 'it begin');
      let a = 'abc';
      let b = 'b';
      
      expect(a).assertContain(b);
      expect(a).assertEqual(a);
    })
  })
}