import { describe, beforeAll, beforeEach, afterEach, afterAll, it, expect } from '@ohos/hypium';

export default function localUnitTest() {
  describe('localUnitTest', () => {
    
    beforeAll(() => {
      
      
    });
    beforeEach(() => {
      
      
      
    });
    afterEach(() => {
      
      
      
    });
    afterAll(() => {
      
      
    });
    it('assertContain', 0, () => {
      
      let a = 'abc';
      let b = 'b';
      
      expect(a).assertContain(b);
      expect(a).assertEqual(a);
    });
  });
}