export class Constants {
  static readonly BASE_URL = 'https://api.lightnovel.fun';
  static readonly VER_NAME = '0.11.53';
  static readonly VER_CODE = 193;
  static readonly PLATFORM = 'android';
  static readonly CLIENT = 'app';
  static readonly HEADER_USER_AGENT = 'Dart/3.8 (dart:io)';

  
  static readonly THEME_COLOR = '#0AA6A6';

  static readonly BG_COLOR = $r('app.color.app_bg');
  static readonly CARD_BG_COLOR = $r('app.color.card_bg');
  static readonly TEXT_PRIMARY = $r('app.color.text_primary');
  static readonly TEXT_SECONDARY = $r('app.color.text_secondary');
  static readonly DIVIDER_COLOR = '#22808080';  

  
  static readonly PLACEHOLDER_BG = $r('app.color.placeholder_bg');
  static readonly DISABLED_FG = $r('app.color.disabled_fg');
  static readonly DISABLED_BG = $r('app.color.disabled_bg');
  static readonly THEME_TINT_BG = $r('app.color.theme_tint_bg');
  static readonly THEME_TINT_BG_STRONG = $r('app.color.theme_tint_bg_strong');
  static readonly EXP_BAR_BG = $r('app.color.exp_bar_bg');
  static readonly DIALOG_CANCEL = $r('app.color.dialog_cancel');
}
